/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardItem: typeof import('./src/components/CardItem/index.vue')['default']
    CodeEdit: typeof import('./src/components/CodeEdit/index.vue')['default']
    Codemirrors: typeof import('./src/components/Codemirrors/index.vue')['default']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Main: typeof import('./src/components/Main/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
    Video: typeof import('./src/components/Video/index.vue')['default']
  }
}
